name: deep-live-cam

channels:
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - numpy=1.23.5
  - onnx=1.16.0
  - tqdm=4.66.4

  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch==2.0.1+cu118
    - torchvision==0.15.2+cu118
    - psutil==5.9.8
    - tensorflow==2.12.1
    - gfpgan==1.3.8
    - opencv-python==4.8.1.78
    - insightface==0.7.3
    - onnxruntime-gpu==1.18.0
    - customtkinter==5.2.2
    - pillow==9.5.0
    - protobuf==4.23.2
    - opennsfw2==0.10.2
    - tk==0.1.0
